#apiVersion: monitoring.coreos.com/v1
#kind: ServiceMonitor
#metadata:
#  name: monitor-k8s01-frontend
#  labels:
#    name: monitor-k8s01-frontend
#    release: prometheus
#spec:
#  selector:
#    matchLabels:
#      name: svc-k8s01-frontend
#  endpoints:
#    - port: http-traffic
#      path: "/actuator/prometheus"
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    release: prometheus
  name: monitor-k8s01-backend
spec:
  namespaceSelector:
    matchNames:
      - default
  selector:
    matchLabels:
      type: svc-k8s01-backend
  endpoints:
    - port: web

