### index
GET http://localhost:8080

### actuator
GET http://localhost:8080/actuator

### prometheus
GET http://localhost:8080/actuator/prometheus


###
POST http://localhost:9090/api/v1/query

{}

###