backend:
    url: http://localhost:9090
logging:
    level:
        org:
            springframework:
                web:
                    client: DEBUG
server:
    port: 8080

spring:
    application:
#        name: @project.artifactId@
        name: k8s01-frontend
management:
    endpoints:
        web:
            exposure:
                include: health, metrics, prometheus
    metrics:
        tags:
            application: ${spring.application.name}
