apiVersion: skaffold/v3
kind: Config
build:
  artifacts:
    - image: k8s05-backend
      context: ./k8s05-backend
      jib: {}

    - image: k8s05-frontend
      context: k8s05-frontend
      jib: {}

profiles:
  - name: gcb
    build:
      googleCloudBuild: {}


manifests:
  rawYaml:
  - k8s/backend.yml
  - k8s/frontend.yml



portForward:
  - resourceType: service
    resourceName: scv-backend
    namespace: default
    port: 8080
    localPort: 8088 # *Optional*

  - resourceType: service
    resourceName: scv-frontend
    namespace: default
    port: 8080
    localPort: 8080 # *Optional*