version: '3.9'
services:
  mysql:
    container_name: "mysql_8_0_27"        # 指定容器的名称
    image: "mysql:8.0.27"              # 指定镜像和版本
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_HOST=%
      - MYSQL_ROOT_PASSWORD=root
#      - TZ=Asia/Taipei
      - MYSQL_DATABASE=jpa
      - MYSQL_USER=tommy
      - MYSQL_PASSWORD=tommy
    volumes:
      - "./data/mysql8:/var/lib/mysql"  # 挂载数据目录
    command:
      - --lower_case_table_names=1                             # 忽略大小写
      - --default-authentication-plugin=mysql_native_password  # 使用本地存储密码
#      - --default-time-zone=+08:00
    security_opt:
      - seccomp:unconfined
