version: '3.9'
services:
  redis7:
    container_name: redis-server
    image: redis:7.0.5-alpine
    ports:
      - 6379:6379
    restart: always
    volumes:
      - ./conf/redis.conf:/usr/local/etc/redis/redis.conf
      - ./data:/data
