version: '3.9'
services:
  redis7:
    container_name: redis7
    image: redis:7.0.5-alpine
#    privileged: true  # 启动特权模式
#    sysctls:
#      net.core.somaxconn: 10240
#      net.ipv4.tcp_syncookies: 0
    ports:
      - 6379:6379
    restart: always
    volumes:
      - ./conf/redis.conf:/usr/local/etc/redis/redis.conf
      - ./data:/data
#    command: # 多个命令同时执行
#      - /bin/bash
#      - -c
#      - |
#        echo 551 > /proc/sys/net/core/somaxconn
#        sysctl vm.overcommit_memory=1
#        redis-server /etc/redis.conf --appendonly yes
