logging:
    level:
        org:
            springframework:
                web:
                    client: DEBUG
server:
    port: 9090
spring:
    application:
        name: @project.artifactId@
management:
    endpoints:
        web:
            exposure:
                include: health, metrics, prometheus
    metrics:
        tags:
            application: ${spring.application.name}