apiVersion: skaffold/v3
kind: Config

metadata:
  name: k8s-04-skaffold-kustomization

build:
  artifacts:
  - image: k8s-04-skaffold-kustomization
    context: .
    jib: {}

deploy:
  kustomize:
    paths:
    - kustomization/base

profiles:
  # Local cluster - we build and deploy things locally
  - name: local
    build:
      local:
        push: false
#    activation:
#      - kubeContext: docker-desktop
  # AWS EKS - does not build anything and will just push local images to remote ECR
  - name: aws
    deploy:
      kustomize:
        paths:
          - kustomization/aws
