apiVersion: skaffold/v3
kind: Config

metadata:
  name: k8s-04-skaffold-kustomization

build:
  artifacts:
    - image: k8s-04-skaffold-kustomization
      context: .
      jib: {}

manifests:
  kustomize:
    paths:
      - k8s/overlays/dev


deploy:
  kubectl: {}

profiles:
  - name: prod
    manifests:
      kustomize:
        paths:
          - overlays/prod


