version: '3'
services:
  web:
    build: .
    ports:
      - 8080:8080
    volumes:
      - .:/code
  prometheus:
    image: bitnami/prometheus:latest
    container_name: prometheus
    volumes:
      - ./env/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./data/prometheus-persistence:/opt/bitnami/prometheus/data
    ports:
      - 9090:9090
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000
    env_file:
      - ./env/grafana.env

