apiVersion: apps/v1
kind: Deployment
metadata:
  name: dp-backend
spec:
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: k8s06-backend
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: scv-backend
spec:
  ports:
    - port: 8080
      name: http
  type: LoadBalancer
  selector:
    app: backend