logging:
  level:
    root: INFO
    org:
      hibernate:
        SQL: DEBUG
        type: TRACE

spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:test
    password: ''
    username: sa
  h2:
    console:
      enabled: true
  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.H2Dialect
