logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type: TRACE
    root: INFO


spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:test
    password: ''
    username: sa
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
