version: '3.2'

services:
  mysql57:
    image: mysql:5.7
    ports:
      - "3306:3306"
    volumes:
      - ./data/mysql5:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - TZ=Asia/Taipei
      - MYSQL_DATABASE=jpa
      - MYSQL_USER=tommy
      - MYSQL_PASSWORD=tommy
    command: [ 'mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci','--default-time-zone=+08:00' ]