# https://www.lagou.com/lgeduarticle/103649.html
#
# intellij plugin
# kafkalytic
# zoolytic--zookeeper-tool

version: '3.7'

services:
  zookeeper01:
    image: zookeeper:3.4.9
    container_name: zookeeper01
    hostname: zookeeper01
    ports:
      - "2181:2181"
    environment:
      ZOO_MY_ID: 1
      ZOO_PORT: 2181
      ZOO_SERVERS: server.1=zookeeper01:2888:3888
    volumes:
      - ./data/zookeeper01/data:/data
      - ./data/zookeeper01/datalog:/datalog

  kafka01:
    image: confluentinc/cp-kafka:5.4.0
    container_name: kafka01
    hostname: kafka01
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: LISTENER_DOCKER_INTERNAL://kafka01:19092,LISTENER_DOCKER_EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_DOCKER_INTERNAL:PLAINTEXT,LISTENER_DOCKER_EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER_INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper01:2181"
      KAFKA_BROKER_ID: 1
      KAFKA_LOG4J_LOGGERS: "kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"
    volumes:
      - ./data/kafka01/data:/var/lib/kafka/data
    depends_on:
      - zookeeper01
