name: build gradle project
on:
  push:
    branches:
      - main
    paths:
      - 'getting-started-guides/02-gs-consuming-rest/**'
      - '.github/workflows/build-gradle-project.yml'

jobs:

  gradle-builder:

    runs-on: ubuntu-latest


    steps:
      - name: checkout source code
        uses: actions/checkout@v3
        with:
          fetch-depth: 1


      - name: jdk 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17


      - name: change gradlew Permission
        run: chmod +x ./getting-started-guides/02-gs-consuming-rest/gradlew

      - name: run gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: bootJar
          build-root-directory: ./getting-started-guides/02-gs-consuming-rest




      #########################
      #########################
      #########################

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}


      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./getting-started-guides/02-gs-consuming-rest
          push: true
          tags: yudady/02-gs-consuming-rest:latest
          build-args: JAR_FILE=./build/libs/02-gs-consuming-rest-0.0.1-SNAPSHOT.jar



      #########################
      #########################
      #########################
      # https://slack.com/intl/zh-tw/help/articles/115005265063-Slack-%E5%82%B3%E5%85%A5%E7%9A%84-Webhook
      # https://github.com/marketplace/actions/notify-slack-action
      - name: slack report Status
        uses: ravsamhq/notify-slack-action@v2
        if: always()
        with:
          status: ${{ job.status }}
          token: ${{ secrets.GITHUB_TOKEN }}
          notification_title: "{workflow} has {status_message}"
          message_format: "{emoji} *{workflow}* {status_message} in <{repo_url}|{repo}>"
          footer: "Linked Repo <{repo_url}|{repo}> | <{workflow_url}|View Workflow>"
          notify_when: "success,failure,cancelled,warnings"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}


      # https://axolo.co/blog/p/top-4-github-action-slack-integration
#      - uses: 8398a7/action-slack@v3
#        #        if: always() # Pick up events even if the job fails or is canceled.
#        with:
#          if_mention: 'failure,cancelled'
#          status: ${{ job.status }}
#          fields: repo,message,commit,author,action,eventName,ref,workflow,job,took # selectable (default: repo,message)
#        env:
#          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required




