name: build gradle project
on:
  push:
    branches:
      - main
    paths:
      - 'springboot-environment/**'
      - '.github/workflows/build-gradle-project.yml'

jobs:

  gradle-builder:

    runs-on: ubuntu-latest


    steps:
      - name: checkout source code
        uses: actions/checkout@v3
        with:
          fetch-depth: 1


      - name: jdk 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17


      - name: change gradlew Permission
        run: chmod +x "$GITHUB_WORKSPACE"/getting-started-guides/02-gs-consuming-rest/gradlew

      - name: run gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build
          build-root-directory: getting-started-guides/02-gs-consuming-rest