name: build gradle project
on:
  push:
    branches:
      - main
    paths:
      - 'getting-started-guides/02-gs-consuming-rest/**'
      - '.github/workflows/build-gradle-project.yml'

jobs:

  gradle-builder:

    runs-on: ubuntu-latest


    steps:
      - name: checkout source code
        uses: actions/checkout@v3
        with:
          fetch-depth: 1


      - name: jdk 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17


      - name: change gradlew Permission
        run: chmod +x "$GITHUB_WORKSPACE"/getting-started-guides/02-gs-consuming-rest/gradlew

      - name: run gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build
          build-root-directory: getting-started-guides/02-gs-consuming-rest


      # https://slack.com/intl/zh-tw/help/articles/115005265063-Slack-%E5%82%B3%E5%85%A5%E7%9A%84-Webhook
      # https://github.com/marketplace/actions/notify-slack-action
      - name: slack report Status
        uses: ravsamhq/notify-slack-action@v2
        if: always()
        with:
          status: ${{ job.status }}
          token: ${{ secrets.GITHUB_TOKEN }}
          notification_title: "{workflow} has {status_message}"
          message_format: "{emoji} *{workflow}* {status_message} in <{repo_url}|{repo}>"
          footer: "Linked Repo <{repo_url}|{repo}> | <{workflow_url}|View Workflow>"
          notify_when: "failure"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}







