name: Run Gradle on PRs
on:
  push:
    branches:
      - main
    paths:
      - 'getting-started-guides/01-gs-rest-service/**'
      - '.github/workflows/build-maven-01-gs-rest-service.yml'

jobs:
  gradle:

    runs-on: ubuntu-latest

#    defaults:
#      run:
#        shell: bash
#        working-directory: getting-started-guides/01-gs-rest-service

    steps:
      - name: checkout source code
        uses: actions/checkout@v3
        with:
          fetch-depth: 1


      - name: jdk 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: echo-GITHUB_WORKSPACE
        run: echo "$GITHUB_WORKSPACE"


      - name: Setup Maven Action
        uses: s4u/setup-maven-action@v1.5.0
        with:
          java-version: 17
          maven-version: 3.8.6


      - name: echo-build-folder
        run: ls -la

      - name: pwd "$GITHUB_WORKSPACE"
        run: pwd

      - name: run maven
        run: mvn -V
        working-directory: getting-started-guides/01-gs-rest-service
