name: Run Gradle on PRs
on:
  push:
    branches:
      - main
    paths:
      - 'springboot-environment/**'
      - '.github/workflows/build-gradle-springboot-environment.yml'

jobs:
  gradle:

    runs-on: ubuntu-latest

    steps:
      - name: checkout source code
        uses: actions/checkout@v3

      - name: jsk 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: go into springboot-environment folder
        run: |
          cd ./springboot-environment

      - name: list folder files
        run: tree .

      - name: Execute Gradle build
        run: ./gradlew clean build