name: test github action

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/test-github-action.yml'
      - '.github/workflows/scripts/test-github-action.sh'

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: echo command
        run: |
          echo "==================================="
          echo "GO!!!!!!!!!!!!!!!!!!!!!"
          echo "==================================="
  job2:
    needs: job1
    runs-on: ubuntu-latest
    steps:
      - name: echo command
        run: |
          echo "==================================="
          echo "GO!!!!!!!!!!!!!!!!!!!!!"
          echo "==================================="  

  job3:
    runs-on: ubuntu-latest
    steps:
      - name: echo command
        run: |
          echo "==================================="
          echo "GO!!!!!!!!!!!!!!!!!!!!!"
          echo "==================================="


  test-shell:
    needs: job2
    runs-on: ubuntu-latest
    steps:

      - name: checkout source code
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: run shell
        run: sh ./.github/workflows/scripts/test-github-action.sh

      - name: run test-github-action.sh end
        run: |
          echo "==========done========================="
  

  test-command:
    runs-on: ubuntu-latest
    steps:
      - name: echo command
        run: |
          echo "==================================="
          echo "run : ls -la"
          ls -la
          echo ""
          echo "run : pwd"
          pwd
          echo ""
          echo "==================================="

  depends-on-other-jobs:
    needs: [ test-shell, test-command ,job3 ]
    runs-on: ubuntu-latest
    steps:
      - name: echo command
        run: |
          echo "==================================="
          echo "GO!!!!!!!!!!!!!!!!!!!!!"
          echo "==================================="  
          
          
