name: test github action

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/test-github-action.yml'

jobs:
  test-github-action:
    runs-on: ubuntu-latest
    steps:

      - name: checkout source code
        uses: actions/checkout@v3
        with:
          fetch-depth: 1



      - name: Retrieve secret
        env:
          super_secret: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: echo "$slack_webhook_url"

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: test
        run: sh ./ci.sh

      - name: run shell end
        run: |
          echo "==========run shell end========================="
          echo "==========run shell end========================="
          echo "==========run shell end========================="
          echo "==================================="
          echo "==================================="
          echo "==================================="
          echo "==================================="
          echo "==================================="
          echo "==================================="
          echo "==================================="
          ls -la
          pwd
