name: test github action

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/test-github-action.yml'

jobs:
  test-github-action:
    runs-on: ubuntu-latest
    steps:
      - name: Retrieve secret
        env:
          super_secret: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: echo "$slack_webhook_url"

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: run shell
        run: .github/workflows/shells/test-github-action.sh