backend:
    url: http://scv-backend:8080
logging:
    level:
        org:
            springframework:
                web:
                    client: DEBUG
server:
    port: 8080

spring:
    application:
        name: @project.artifactId@
management:
    endpoints:
        web:
            exposure:
                include: health, metrics, prometheus
    metrics:
        tags:
            application: ${spring.application.name}
